### ISSUE TITLE
train.py: error: unrecognized arguments: --online --endpoints endpoints.yml

### ISSUE THREAD

**Issue by Zengpr** [GaoQ1/rasa_chatbot_cn#13]
when train dialogue in online mod, it traceback:
train.py: error: unrecognized arguments: --online --endpoints endpoints.yml

**Comment by GaoQ1** [comment]
please read requirements.txt, it maybe version's problem.

**Comment by GaoQ1** [comment]
[this issue](https://github.com/GaoQ1/rasa_chatbot_cn/issues/11) give a solution.

**Comment by Zengpr** [comment]
我是这样安装的,版本都对的上,就是在train dialogue in online mod训练的时候有这个问题,要怎么改命令呢

**Comment by gaoxing153** [comment]
Is the content of this demo changed to the medical field, or is the original rasa_chatbot code?

**Comment by GaoQ1** [comment]
> Is the content of this demo changed to the medical field, or is the original rasa_chatbot code?

demo和medical的代码有所不同，业务场景、需求和细节不同。

**Comment by gaoxing153** [comment]
我现在在做老师的一个医疗领域的问答系统，现在遇到了一些困难，我有一些问题想向你请教一下：
1.你的医疗领域的代码是在rasa_chatbot的基础上进行修改的么？
2.你在编写代码的时候你的医疗相关的数据是存储在那里的？

**Comment by GaoQ1** [comment]
有修改，存储数据库。

**Comment by gaoxing153** [comment]
整个过程的工作量大么，我想用rasa做，但是现在时间不是太充足

**Comment by GaoQ1** [comment]
工作量主要体现在你数据的处理标注，以及story的编写。这个要看你数据量的情况了。

**Comment by gaoxing153** [comment]
目前数据库的是7万条数据，不过时间比较赶的话，我可以先只处理其中一部分数据即可，后面可以再加，故事编写的话，目前并不需要很多的对话场景，有几种就行，如果是这种情况的话工作量大概是多久？

**Comment by Zengpr** [comment]
能否定义实体类型字典呢,类似感冒/扁桃体发炎为disease,鸡蛋/番茄为food,直接在训练数据里加的话会不会太大了
@[disease]
    ~[感冒]
    ~[肢端肥大症]
    ~[血劳]
    ~[胃型哮喘]
    ~[甲状腺癌]
	
@[food]
    ~[木耳粥]
    ~[鸡蛋]
    ~[芦笋鸡丝汤]
    ~[桃仁]
    ~[桂皮]

**Comment by GaoQ1** [comment]
@Zengpr 非常好的问题，定义实体类型字典这个我还没写component支持，是可以实现的。我们现在是在人名地名机构名这块有这个问题，所以我引入了jieba的词性标注加以支持的。
或者我在想是不是可以你给出足够多的实体在训练数据中，然后通过bert进行finetune，bert转词向量后应该会学到这块的内容。

**Comment by zhangyanbo2007** [comment]
@Zengpr  我是这样安装的,版本都对的上,就是在train dialogue in online mod训练的时候有这个问题,要怎么改命令呢,不是启动server，想知道你后来是怎么解决的。

**Comment by zhangyanbo2007** [comment]
训练的时候把这个--online --endpoints endpoints.yml 去掉
把python -m rasa_core.train --online -o models/dialogue -d mobile_domain.yml -s data/mobile_story.md --endpoints endpoints.yml
改成
python -m rasa_core.train -o models/dialogue -d mobile_domain.yml -s data/mobile_story.md
就可以了，
但是这样的话不就没有在线更新了吗？

**Comment by zhangyanbo2007** [comment]
还请楼主回答

**Comment by GaoQ1** [comment]
这个应该是rasa-core的问题，建议去[rasa-core](https://github.com/RasaHQ/rasa_core/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+online)这里看看

**Comment by Zengpr** [comment]
@zhangyanbo2007 这个问题我没有解决
@GaoQ1 我加入了越多实体到训练数据，bert的测试集准确率越低（甚至低于0.1），少点时达到百分之80\90。另外，实体识别始终是大问题呀，很多都是识别不了的，各种组件的都试了。
我识别的是菜名，用ner_mitie的话，字典没加的也是识别不了的呀。

**Comment by red-frog** [comment]
https://rasa.com/docs/core/0.13.3/interactive_learning/
最新的版本使用这条命令可以解决这个问题
@Zengpr
