### ISSUE TITLE
想问下这个多轮对话怎么能跟FAQ问答结合在一起使用呢？

### ISSUE THREAD

**Issue by zhangyanbo2007** [GaoQ1/rasa_chatbot_cn#15]
FAQ问答一般是通过知识库的检索+匹配两阶段过程，跟意图识别+对话管理好像不是一个思路。如果把FAQ问答和多轮对话以及闲聊做三项集成，我考虑是不是可以这样，先用意图识别看是否是多轮对话story里面包含的意图，如果不在范围内，就直接走检索阶段，如果检索OK就通过FAQ进行匹配，如果检索不OK就走闲聊。期待您的回复。

**Comment by GaoQ1** [comment]
可以这样做，这个取决于你们业务。或者你可以设定一个意图为需要知识库的检索，识别为那个意图就去走检索。

**Comment by GaoQ1** [comment]
知识检索如果都是问句，形式差不多的话，其实意图应该还是比较好识别出来的。

**Comment by zhangyanbo2007** [comment]
非常感谢，我现在先复现您的工程，再分析怎么加进去FAQ。

**Comment by xxllp** [comment]
我也在这块可以一起探讨下 @zhangyanbo2007
