### ISSUE TITLE
意图识别并没有结合命名实体识别的特征，只有结巴特征，我认为这个对意图识别有影响

### ISSUE THREAD

**Issue by zhangyanbo2007** [GaoQ1/rasa_chatbot_cn#21]
我发现一个问题，意图识别的特征向量的分词没有考虑命名实体识别而是直接拿的结巴分词的特征，比方说，用户语料里面标的实体是“中华人民共和国”，但是结巴分词不能对其做整体命名识别，只能识别“中华”，“人民”，“共和国”，这个我认为对识别意图是有影响的，你觉得呢？

**Comment by zhangyanbo2007** [comment]
方便加个微信吧，我的微信15821444815，多交流！

**Comment by GaoQ1** [comment]
你可以进820037374 rasa中文官方社区

**Comment by red-frog** [comment]
820037374 rasa 中文群，入群答案不是RASA吗？

**Comment by GaoQ1** [comment]
直接申请就行了吧

**Comment by zhangyanbo2007** [comment]
早就加了，你也在里面啊，哪位？哈哈

**Comment by GaoQ1** [comment]
coin
