### ISSUE TITLE
库文件缺少啊

### ISSUE THREAD

**Issue by viaco2ove** [GaoQ1/rasa_chatbot_cn#22]
我自己整理一下，不知道对不对
numpy==1.14.5
jsonschema==2.6
pyyaml==3.12
packaging==17.0
setuptools == 39.1.0
sklearn_crfsuite
jieba
duckling
keras
##twisted
rasa-nlu == 0.13.4
rasa-nlu-gao == 0.2.0
rasa-core == 0.12.3
rasa-core-sdk == 0.12.1

**Comment by viaco2ove** [comment]
1.python 3.6

2.下载安装Twisted

pip install F:\windows_bak\user\Administrator\Desktop\Twisted-18.9.0-cp36-cp36m-win_amd64.whl

3.下载安装setuptools-39.1.0
pip uninstall  setuptools
pip install setuptools == 39.1.0

4.JPype1  下载安装JPype1-0.6.3-cp36-cp36m-win_amd64.whl
pip install F:\windows_bak\user\Administrator\Desktop\JPype1-0.6.3-cp36-cp36m-win_amd64.whl

pip uninstall  numpy

pip uninstall  jsonschema

pip uninstall  packaging

pip uninstall  pyyaml

**Comment by GaoQ1** [comment]
请拉取最新的代码尝试下，这些问题都不会存在的
