### ISSUE TITLE
启动完了，能做些啥？看着命令台发呆？

### ISSUE THREAD

**Issue by viaco2ove** [GaoQ1/rasa_chatbot_cn#23]

**Comment by GaoQ1** [comment]
启动完了，可以调用服务，就是一个对话服务，可以聊天。

**Comment by Ellenyan123** [comment]
大牛，您好！启动后在Your input 输入一句话后就会自动跳出呢，有什么办法能解决这个问题？

**Comment by Ellenyan123** [comment]
Your input ->  /greet   和  Your input ->  你好  都会自动跳出
