### ISSUE TITLE
Unknown layer:name

### ISSUE THREAD

**Issue by NexusLee** [GaoQ1/rasa_chatbot_cn#24]
试了tensorflow 1.9，1.10，1.12 py版本也试了3.6.6 怎么都是这个错

**Comment by GaoQ1** [comment]
是训练rasa-core还是rasa-nlu？

**Comment by NexusLee** [comment]
@GaoQ1 我是直接跑你生成好的dialog 难道不行的吗

**Comment by GaoQ1** [comment]
要不你重新训练试试

**Comment by NexusLee** [comment]
@GaoQ1 我重新训练了 train-nlu-gao，但我有点尴尬，我跑起了actions，但我找了半天文档没找到怎么跑 rasa_core.run

**Comment by NexusLee** [comment]
@GaoQ1  python -m rasa_core.run --nlu models/nlu_gao/default/current --core 后面不知道命令了

**Comment by zylhub** [comment]
@NexusLee 参考rasa_nlu 给出的 keras、tensorflow版本号，

- tensorflow==1.12.0
- keras-applications==1.0.6
- keras-preprocessing==1.0.5

**Comment by NexusLee** [comment]
@zylhub 我重新训练模型了
