### ISSUE TITLE
自己训练的效果不是很理想呢

### ISSUE THREAD

**Issue by NexusLee** [GaoQ1/rasa_chatbot_cn#26]
![image](https://user-images.githubusercontent.com/4703440/55391449-f4e4ae80-556b-11e9-933d-96a7ba85dcb4.png)

用 gao 模型 和 keras 对话训练

**Comment by jiangdongguo** [comment]
是训练的数据量太少了吧？导致置信度太低

**Comment by GaoQ1** [comment]
这个多方面的问题，component的选择，训练数据，policy的选择等等
