### ISSUE TITLE
从《SeqGAN训练生成小黄鸡语料》而来，但是没有找到项目代码

### ISSUE THREAD

**Issue by LL-Li** [GaoQ1/rasa_chatbot_cn#27]
hello，从《SeqGAN训练生成小黄鸡语料》而来，但是没有找到项目代码，请问您方便提供一下吗？非常感谢！

**Comment by GaoQ1** [comment]
我有写过这方面的文章吗？链接是啥的？

**Comment by LL-Li** [comment]
> 我有写过这方面的文章吗？链接是啥的？

https://python.ctolib.com/GaoQ1-seqgan.html

**Comment by GaoQ1** [comment]
额，这个不知道怎么抓的我的项目，我已经把这个项目设为private

**Comment by LL-Li** [comment]
> 额，这个不知道怎么抓的我的项目，我已经把这个项目设为private

(｀･д･′)真是令人头秃，那请问您方便提供一下代码吗？我正好也在做用seqgan做中文文本生成这方面的工作，您的工作对我很有帮助，我很想学习一下，不会拿来做其他用途的。

**Comment by LL-Li** [comment]
> 邮箱是啥

347882431@qq.com 非常感谢！

**Comment by GaoQ1** [comment]
已发

**Comment by LL-Li** [comment]
> 已发

收到，再次感谢

**Comment by yfzuo** [comment]
Hi，我也想要一份做中文的seq-gan的代码，不知道楼主方便给一下吗？邮箱是2017983051@qq.com

**Comment by GaoQ1** [comment]
https://github.com/GaoQ1/seqgan  这个打不开吗？
