### ISSUE TITLE
python bot.py train-nlu-gao失败，请问如何处理？

### ISSUE THREAD

**Issue by jiangdongguo** [GaoQ1/rasa_chatbot_cn#29]
TimeoutError: no response from the server (with "timeout"=10000 ms), please check the following:is the server still online? is the network broken? are "port" and "port_out" correct? ar
e you encoding a huge amount of data whereas the timeout is too small for that?

其中，已经执行 bert-serving-start -model_dir /tmp/chinese_L-12_H-768_A-12/ -num_worker=4

日志：

                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = E:\Environment\python\chinese_L-12_H-768_A-12
          num_worker = 4
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:?[35mVENTILATOR?[0m:freeze, optimize and export graph, could take a while...
I:?[36mGRAPHOPT?[0m:model config: E:\Environment\python\chinese_L-12_H-768_A-12\bert_config.json
I:?[36mGRAPHOPT?[0m:checkpoint: E:\Environment\python\chinese_L-12_H-768_A-12\bert_model.ckpt
I:?[36mGRAPHOPT?[0m:build graph...
I:?[36mGRAPHOPT?[0m:load parameters from checkpoint...
I:?[36mGRAPHOPT?[0m:optimize...
I:?[36mGRAPHOPT?[0m:freeze...
I:?[36mGRAPHOPT?[0m:write graph to a tmp file: C:\Users\Jiangdg\AppData\Local\Temp\tmpc8m5mmy8
I:?[35mVENTILATOR?[0m:optimized graph is stored at: C:\Users\Jiangdg\AppData\Local\Temp\tmpc8m5mmy8
I:?[35mVENTILATOR?[0m:bind all sockets
I:?[35mVENTILATOR?[0m:open 8 ventilator-worker sockets
I:?[35mVENTILATOR?[0m:start the sink
I:?[32mSINK?[0m:ready
I:?[35mVENTILATOR?[0m:get devices
W:?[35mVENTILATOR?[0m:only 1 out of 1 GPU(s) is available/free, but "-num_worker=4"
W:?[35mVENTILATOR?[0m:multiple workers will be allocated to one GPU, may not scale well and may raise out-of-memory
I:?[35mVENTILATOR?[0m:device map:
                worker  0 -> gpu  0
                worker  1 -> gpu  0
                worker  2 -> gpu  0
                worker  3 -> gpu  0
I:?[33mWORKER-1?[0m:use device gpu: 0, load graph from C:\Users\Jiangdg\AppData\Local\Temp\tmpc8m5mmy8
I:?[33mWORKER-3?[0m:use device gpu: 0, load graph from C:\Users\Jiangdg\AppData\Local\Temp\tmpc8m5mmy8
I:?[33mWORKER-2?[0m:use device gpu: 0, load graph from C:\Users\Jiangdg\AppData\Local\Temp\tmpc8m5mmy8
I:?[33mWORKER-0?[0m:use device gpu: 0, load graph from C:\Users\Jiangdg\AppData\Local\Temp\tmpc8m5mmy8

**Comment by GaoQ1** [comment]
超时的问题，你应该是没有起bert server服务

**Comment by jiangdongguo** [comment]
请问这执行如下命令启动吗？

 bert-serving-start -model_dir /tmp/chinese_L-12_H-768_A-12/ -num_worker=4

这个命令我已经执行了，但是看不出是否已经启动

**Comment by cabbageNoob** [comment]
我也遇到了和你一样的问题，请问这个问题解决了吗

**Comment by GaoQ1** [comment]
启动完了之后可以通过bert-serving-client调动，建议去[bert-as-server](https://github.com/hanxiao/bert-as-service)看看用法
