### ISSUE TITLE
请问训练好的模型可以直接当成rasa_nlu模型使用吗？

### ISSUE THREAD

**Issue by sjyu2011** [GaoQ1/rasa_chatbot_cn#3]

**Comment by GaoQ1** [comment]
没听懂啥意思

**Comment by GaoQ1** [comment]
你如果用我的rasa_nlu_gao训练生成模型的话，就也用python -m rasa_nlu_gao.server启动模型服务。rasa_nlu不一定跑的通。因为我在rasa_nlu_gao中自定义好几种component,这些rasa_nlu是没有的。我的rasa_nlu_gao是在rasa_nlu 0.13.4基础上加的

**Comment by sjyu2011** [comment]
>           你如果用我的rasa_nlu_gao训练生成模型的话，就也用python -m rasa_nlu_gao.server启动模型服务。rasa_nlu不一定跑的通。因为我在rasa_nlu_gao中自定义好几种component,这些rasa_nlu是没有的。我的rasa_nlu_gao是在rasa_nlu 0.13.4基础上加的

如果要在rasa_core中使用，可以吗？
