### ISSUE TITLE
请问nlu训练样本中，unknown_intent的作用是？

### ISSUE THREAD

**Issue by jiangdongguo** [GaoQ1/rasa_chatbot_cn#30]

**Comment by GaoQ1** [comment]
maybe是为了out-of-scope

**Comment by jiangdongguo** [comment]
谢谢回复！还有个问题想请教下，就是如何完善story.md，我这里只考虑了期望中的对话流样本，对于一些异常情况不知道怎么设计对话流样本，请问该如何处理，或如果能够参考下你实际项目中的story.md就更感谢了(765067602@qq.com)？另外，FormAction会不会在设计story方面比较方便？辛苦了，谢谢！

**Comment by GaoQ1** [comment]
story.md这个需要结合业务设计的，需要不断完善修改。如果不在你设计的意图里面就考虑走out-of-scope，放个安全性的回答吧。

**Comment by jiangdongguo** [comment]
请问out-of-scope是否就是(类似)rasa core提供的utter_default？谢谢！

**Comment by GaoQ1** [comment]
嗯，类似
