### ISSUE TITLE
默认pip install -r requirements.txt报错，能否升级下

### ISSUE THREAD

**Issue by cancoo** [GaoQ1/rasa_chatbot_cn#31]
我使用conda新建了一个干净的环境，python=3.6.8
然后，pip install -r requirements.txt，报错：

`ERROR: tensorflow 1.10.0 has requirement numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.16.3 which is incompatible.
ERROR: tensorflow 1.10.0 has requirement setuptools<=39.1.0, but you'll have setuptools 41.0.1 which is incompatible.
ERROR: rasa-core 0.12.3 has requirement jsonschema~=2.6, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: rasa-core 0.12.3 has requirement packaging~=17.0, but you'll have packaging 19.0 which is incompatible.
ERROR: rasa-core 0.12.3 has requirement pyyaml~=3.12, but you'll have pyyaml 5.1 which is incompatible.`

看了下，这些包都是pip关联安装的，版本已经不对了，
1、能否麻烦共享下您的python版本，还有全部的requirements.txt
2、不知能否升级下rasa_nlu，新版本的nlu变化很大了
谢谢！

**Comment by cancoo** [comment]
update...

上面问题，通过更改对应报错的包的版本就可以解决。。。

但是依然有一个包，找不到，duckling。已经通过pip install duckling安装成功，但在执行python bot.py train-nlu的时候，依然报错信息如下：（看了已经关闭的问题，之前也有同学碰过同样的问题，不知道后来是如何解决的，求教，谢谢~~~）
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install duckling

------------------分割线--------------------

贴出我的pip全部的包信息
$ pip list
Package             Version  
------------------- ---------
absl-py             0.7.1    
APScheduler         3.6.0    
astor               0.7.1    
attrs               19.1.0   
Automat             0.7.0    
boto3               1.9.146  
botocore            1.12.146 
certifi             2019.3.9 
chardet             3.0.4    
Click               7.0      
cloudpickle         1.0.0    
colorclass          2.2.0    
coloredlogs         10.0     
colorhash           1.0.2    
ConfigArgParse      0.13.0   
constantly          15.1.0   
cycler              0.10.0   
decorator           4.4.0    
docopt              0.6.2    
docutils            0.14     
duckling            1.8.0    
fakeredis           0.10.3   
fbmessenger         5.6.0    
Flask               1.0.2    
Flask-Cors          3.0.7    
Flask-JWT-Simple    0.0.3    
future              0.17.1   
gast                0.2.2    
gevent              1.4.0    
greenlet            0.4.15   
grpcio              1.20.1   
h5py                2.9.0    
humanfriendly       4.18     
hyperlink           19.0.0   
idna                2.8      
incremental         17.5.0   
itsdangerous        1.1.0    
jieba               0.39     
Jinja2              2.10.1   
jmespath            0.9.4    
JPype1              0.6.3    
jsonpickle          0.9.6    
jsonschema          2.6.0    
Keras               2.2.4    
Keras-Applications  1.0.7    
Keras-Preprocessing 1.0.9    
kiwisolver          1.1.0    
klein               17.10.0  
Markdown            3.1      
MarkupSafe          1.1.1    
matplotlib          2.2.4    
mattermostwrapper   2.1      
networkx            2.3      
numpy               1.14.5   
packaging           17.1     
pathlib             1.0.1    
pika                0.11.2   
pip                 19.1.1   
prompt-toolkit      1.0.14   
protobuf            3.7.1    
pydot               1.4.1    
Pygments            2.4.0    
PyHamcrest          1.9.0    
PyInquirer          1.0.3    
PyJWT               1.7.1    
pykwalify           1.6.0    
pymongo             3.8.0    
pyparsing           2.4.0    
PySocks             1.7.0    
python-crfsuite     0.9.6    
python-dateutil     2.8.0    
python-engineio     3.5.1    
python-socketio     2.1.2    
python-telegram-bot 10.1.0   
pytz                2018.9   
PyYAML              3.13     
rasa-core           0.12.3   
rasa-core-sdk       0.12.1   
rasa-nlu            0.13.4   
rasa-nlu-gao        0.2.0    
redis               2.10.6   
regex               2019.4.14
requests            2.21.0   
requests-toolbelt   0.9.1    
rocketchat-API      0.6.31   
ruamel.yaml         0.15.94  
s3transfer          0.2.0    
scikit-learn        0.19.2   
scipy               1.2.1    
setuptools          39.1.0   
simplejson          3.16.0   
six                 1.12.0   
sklearn-crfsuite    0.3.6    
slackclient         1.3.1    
tabulate            0.8.3    
tensorboard         1.10.0   
tensorflow          1.10.0   
termcolor           1.1.0    
terminaltables      3.1.0    
tqdm                4.31.1   
twilio              6.26.3   
Twisted             19.2.0   
typing              3.6.6    
tzlocal             1.5.1    
urllib3             1.24.3   
wcwidth             0.1.7    
webexteamssdk       1.1.1    
websocket-client    0.54.0   
Werkzeug            0.15.2   
wheel               0.33.2   
zope.interface      4.6.0

**Comment by GaoQ1** [comment]
duckling看你这是有了，应该不会报没有package的错误了。你pipeline用的是duckling还是duckling-http?生产中这儿使用的新版本的，这个demo没做及时更新，也没啥必要更新就没弄。或者你可以试试docker

**Comment by wuyongdec** [comment]
When pip install requirements,I meet the problem blelow,
`
ERROR: tensorflow 1.10.0 has requirement numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.16.3 which is incompatible.
ERROR: tensorflow 1.10.0 has requirement setuptools<=39.1.0, but you'll have setuptools 41.0.1 which is incompatible.
ERROR: rasa-core 0.12.3 has requirement jsonschema~=2.6, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: rasa-core 0.12.3 has requirement packaging~=17.0, but you'll have packaging 19.0 which is incompatible.
ERROR: rasa-core 0.12.3 has requirement pyyaml~=3.12, but you'll have pyyaml 5.1 which is incompatible.
`

I use MacOs 10.14.4 and python 3.6.5

**Comment by cancoo** [comment]
解决了
pip install --upgrade numpy
可以解决duckling的问题
`Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install duckling`

但是最新版本的numpy和tensorflow1.0冲突
`ERROR: tensorflow 1.10.0 has requirement numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.16.3 which is incompatible.`

所以应该有某个版本的numpy能同时和 duckling  & tensorflow1.0 兼容

**Comment by GaoQ1** [comment]
现在已经更新到最新的rasa release版本，这些问题都不存在的

**Comment by carlos9310** [comment]
> 现在已经更新到最新的rasa release版本，这些问题都不存在的
pip install -r requirements.txt时依然存在版本问题

ERROR: rasa 1.1.8 has requirement rasa-sdk~=1.1.0, but you'll have rasa-sdk 1.2.0 which is incompatible.

自己手动降低了rasa-sdk的版本，但是在pip install -r requirements.txt时要怎么确保rasa-sdk的版本与rasa的版本对应呢

**Comment by GaoQ1** [comment]
这个是在install rasa的时候会把依赖的rasa-sdk install
