### ISSUE TITLE
最后如何开始进行对答呢？

### ISSUE THREAD

**Issue by cabbageNoob** [GaoQ1/rasa_chatbot_cn#33]
执行完最后启动了一个 5000端口的服务器 ，访问了一下 ，返回了‘ hello from Rasa NLU: 0.13.4 ’
恩恩 然后怎么开始对答呢？

**Comment by GaoQ1** [comment]
可以通过调用服务器接口进行对答

**Comment by cabbageNoob** [comment]
原谅新手，可否给一个调用服务器接口的例子，比如‘你好’，然后怎么得到其回复呢？  十分感谢

**Comment by GaoQ1** [comment]
`curl -XPOST localhost:5000/parse -d '{"q":"我发烧了该吃什么药？", "project": "rasa_nlu_test", "model": "model_20170921-170911"}' | python -mjson.tool` 建议多看看官方文档
