### ISSUE TITLE
如何贡献代码

### ISSUE THREAD

**Issue by kuhung** [GaoQ1/rasa_chatbot_cn#38]
前辈您好，首先非常感谢您实践了这么一套系统，并为后来人指明了方向。提这个 issue 的目的是想了解如何给该项目贡献，哪些部分是您想优化而一直没有优化的，以及工作流上您是怎么安排的。

小弟不才，也在您的基础上做了部分简化和修改，以方便项目组内的同事使用。修改过程中也发现，实际的代码有部分冗余，也有些配置繁琐的地方；萌生了给代码做贡献的想法。看您的历史提交，似乎只有您一个人在提交。但在文章中，有看到你在号召一起贡献代码。因而产生了矛盾点，希望前辈您能大概表达一下您对这个项目的安排，以及后面规划的功能点。类似 TODO 这种形式，以方便其它人跟进贡献。

最后，再次感谢楼主的贡献~

**Comment by GaoQ1** [comment]
你fork一下代码，然后在你的下面进行修改。提交个pull request就可以了。非常欢迎你能够贡献代码，欢迎。我这个还有还多需要改进的地方的。
