### ISSUE TITLE
博主有人一直看，并感谢你的分享

### ISSUE THREAD

**Issue by tedljw** [GaoQ1/rasa_chatbot_cn#4]
看到博主在踩坑文章6开头的一段话，想告诉博主，其实是有人在看的，只是没有简书的账号，无法表发感谢而已。我浏览了rasa相关的很多实践项目，博主的项目和博客是我看到最具有阅读价值的，我已经把你关于rasa的项目分享给了我的同事。
最后，再对博主的经验分享表示感谢。

**Comment by GaoQ1** [comment]
嗯，知道。互相学习，互相进步。

**Comment by yaleimeng** [comment]
同表感谢。希望 @tedljw 大家也多多发布自己实践的经验。
因为rasa文档语焉不详，即使看完了，也不能很好地从入门到熟练，从0开始把项目做起来，遇到问题也缺乏经验可遵循。

**Comment by tedljw** [comment]
> 同表感谢。希望 @tedljw 大家也多多发布自己实践的经验。
> 因为rasa文档语焉不详，即使看完了，也不能很好地从入门到熟练，从0开始把项目做起来，遇到问题也缺乏经验可遵循。

你可以去我的项目下看看https://github.com/tedljw/rasa_test_ch，同时建议你多看看官方的文档。
