### ISSUE TITLE
用bert yml配置出错了

### ISSUE THREAD

**Issue by OscarLiu2000** [GaoQ1/rasa_chatbot_cn#40]
你好，我用了
language: "zh"

pipeline:
- name: "JiebaTokenizer"
- name: "rasa_nlu_gao.featurizers.bert_vectors_featurizer.BertVectorsFeaturizer"
  ip: '127.0.0.1'
  port: 5555
  port_out: 5556
  show_server_config: True
  timeout: 10000
- name: "rasa_nlu_gao.classifiers.embedding_bert_intent_estimator_classifier.EmbeddingBertIntentEstimatorClassifier"
- name: "SpacyNLP"
- name: "CRFEntityExtractor"

出错文件是：在网上查了但没有找到可用答案  
File "/home/oscar/venv/lib/python3.7/site-packages/rasa/nlu/registry.py", line 196, in create_component_by_config
    return component_class.create(component_config, config)
TypeError: create() takes 2 positional arguments but 3 were given

**Comment by GaoQ1** [comment]
嗯，你重新下载下rasa-nlu-gao==0.3.1，然后看下rasa_chatbot_cn的配置，也修改了。
