### ISSUE TITLE
模型改动到支持英文版本

### ISSUE THREAD

**Issue by OscarLiu2000** [GaoQ1/rasa_chatbot_cn#41]
谢谢分享。如果想支持英文版本是不是要替换

JiebaTokenizer
rasa_nlu_gao.extractors.jieba_pseg_extractor.JiebaPsegExtractor
bert模型

还有别的(bertFeaturizer和bertIntentClassifier) 要替换的吗？rasa官网上有WhitespaceTokenizer， 有没有其他推荐的tokenizer和extractor？

还有集成第三方闲聊接口
train_dialogue在什么地方?
ActionDefaultFallback新版本好像改动了? 怎么加入api的调用？

原谅新手。 如果我有问得不清楚的地方请指出。 

谢谢啦

**Comment by GaoQ1** [comment]
关于支持英文版本还有下面的问题，建议去官方文档看看
