### ISSUE TITLE
Knowledge Graph 心得

### ISSUE THREAD

**Issue by OscarLiu2000** [GaoQ1/rasa_chatbot_cn#45]
谢谢楼主的建议， 现在已经可以支持英文模式了。 在踩坑记中提到会分享写knowledge graph的心得。 请问knowledge graph文本是story.md吗？

每种intent是不是只能一种回答？如果同一个intent但是entity不同能更换回答吗？具体文件在哪里写， 有范例吗？

非常感谢楼主的耐心答疑。谢谢。

**Comment by OscarLiu2000** [comment]
你好， 看了rasa官方文件后，
from rasa_sdk import Action
from rasa_sdk.events import SlotSet

class ActionCheckRestaurants(Action):
   def name(self) -> Text:
      return "action_check_restaurants"

   def run(self,
           dispatcher: CollectingDispatcher,
           tracker: Tracker,
           domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

      cuisine = tracker.get_slot('cuisine')
      q = "select * from restaurants where cuisine='{0}' limit 1".format(cuisine)
      result = db.query(q)

      return [SlotSet("matches", result if result is not None else [])]

对于这两行不太懂：
      q = "select * from restaurants where cuisine='{0}' limit 1".format(cuisine)
      result = db.query(q)
这里db class是要我自己写吗？

像你写的：                "您好，您{}共使用{}二百八十兆，剩余三十兆。".format(time, item))
这里“二百八十兆，剩余三十兆” 是要在一个database里做搜索得出吗？这里database文件是不是放在actions folder下？

**Comment by GaoQ1** [comment]
database可以是一个接口，你在action里面调用
