### ISSUE TITLE
你好，按照你给的配置，训练效果不理想啊

### ISSUE THREAD

**Issue by tengfei7954** [GaoQ1/rasa_chatbot_cn#5]
language: "zh"

 pipeline:
  - name: "tokenizer_jieba"
  - name: "ner_crf"
  - name: "jieba_pseg_extractor"
    part_of_speech: ["nr", "ns", "nt", "nz"]
  - name: "intent_featurizer_count_vectors"
    OOV_token: oov
    token_pattern: '(?u)\b\w+\b'
  - name: "intent_classifier_tensorflow_embedding"
，用的是这个配置，
然后数据格式：
{"entities":[{"start":0,"end":7,"value":"数学","entity":"publiser"}],"text":"数学","intent":"search.publisher"},
{"entities":[{"start":0,"end":7,"value":"大学","entity":"publiser"}],"text":"大学","intent":"search.publisher"},
像这样的组织数据有上万条，训练完成后，比如输入大学，返回的结果意图是空，实体也为空，求解啊

**Comment by tengfei7954** [comment]
训练数据中的“大学”，有这个实体数据啊，到目前在rasa 群里，有好几个伙伴反应都是我这种问题，效果不怎么理想，还有人名，地名的，训练实体中的显示不出来，显示的是jieba的

**Comment by GaoQ1** [comment]
显示的是jieba的因为你加了jieba_pseg_extractor这个组件啊。如果识别不出来那可能是jieba pseg就没能识别出来，因为这个组件内部调用的就是jieba pseg方法。你可以将这个组件去掉，单纯用ner_crf看看实体结果。
