### ISSUE TITLE
你好，我在训练rasa-nlu的时候出现了错误，想请教一下

### ISSUE THREAD

**Issue by wzs951015** [GaoQ1/rasa_chatbot_cn#50]
我自己写了一个component，然后使用这个component进行rasa-nlu的训练，然后出现了如下的错误：
<img width="927" alt="32F7C142-AE93-4892-80C4-8DF1C98D44EF" src="https://user-images.githubusercontent.com/37827394/60880873-17771980-a277-11e9-9766-3b53e92489ee.png">

因为刚接触，所以对这个框架一知半解，希望能够得到您的解答，谢谢~

我在component代码里，只实现了__init__,process和load三个函数，里面并没有train，create等一些函数，是不是这个原因？有哪些函数是创建component必需的？？

**Comment by GaoQ1** [comment]
建议去官方文档查看
