### ISSUE TITLE
关于 install rasa x 的问题，求助

### ISSUE THREAD

**Issue by XuJianzhi** [GaoQ1/rasa_chatbot_cn#52]
您好，
您说在install rasa x时是
pip install rasa-x --extra-index-url https://pypi.rasa.com/simple，
可是国内网络反复retry，反复超时，这个模块国内的镜像也没有，您是怎样解决的？？

**Comment by XuJianzhi** [comment]
我后来在https://pypi.rasa.com/simple/rasa-x/下载了，安装了，，但依然好奇上述问题，服务器未翻墙。

**Comment by GaoQ1** [comment]
网络问题吧，我翻墙的

**Comment by XuJianzhi** [comment]
[import@tst-pg-deeplearning-148 rasa_chatbot_cn]$ make train
rasa train --domain domain.yml --data data --config config.yml --out models
make: rasa: Command not found
make: *** [train] Error 127

您知道这个是为什么吗？是我安装rasa错了吗？？谢谢

**Comment by XuJianzhi** [comment]
我知道了，哈哈
