### ISSUE TITLE
求助：调用第三方api的demo

### ISSUE THREAD

**Issue by Vinbert0203** [GaoQ1/rasa_chatbot_cn#53]
Hi  您好！
对您介绍的内容非常感兴趣，也收获很多。不过自己能力不足，对踩坑记（四）中提到的接第三方api（比如图灵机器人），没有研究明白，所以再向您求教一下。是否有相应的demo share一下，vinbert@qq.com，多谢！

**Comment by GaoQ1** [comment]
这个直接在action里面调用第三方的api就行

**Comment by Vinbert0203** [comment]
Thank U !
