### ISSUE TITLE
bert_service的意图识别

### ISSUE THREAD

**Issue by Ivan-Ji** [GaoQ1/rasa_chatbot_cn#54]
`bert_vectors_featurizer.BertVectorsFeaturizer`在使用的时候，是需要另外开一个`bert_as_service`的服务吗，还是直接按照您写的`rasa_nlu_gao`的默认配置运行就好了呀

**Comment by GaoQ1** [comment]
需要起个bert_as_service服务

**Comment by Ivan-Ji** [comment]
好的，谢谢您
