### ISSUE TITLE
make run时报错

### ISSUE THREAD

**Issue by T-baby** [GaoQ1/rasa_chatbot_cn#55]
Exception: Failed to find component class for 'components.extractors.jieba_pseg_extractor.JiebaPsegExtractor'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module.
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited

**Comment by GaoQ1** [comment]
https://github.com/GaoQ1/rasa_chatbot_cn/blob/master/README.md, you can check `some problems`.
