### ISSUE TITLE
rasa init 时提示rasa不是内部或外部命令

### ISSUE THREAD

**Issue by beanjoe** [GaoQ1/rasa_chatbot_cn#62]
![微信截图_20190903111313](https://user-images.githubusercontent.com/52645844/64141749-d9900f00-ce3b-11e9-9db6-fdfd00a57efe.png)
![image](https://user-images.githubusercontent.com/52645844/64141779-ee6ca280-ce3b-11e9-8720-48bc5631ba36.png)
如图，rasa init 不能执行，环境已经装好了，请教一下这可能是什么问题？

**Comment by GaoQ1** [comment]
你版本下的不对，rasa要下>1.0版本的

**Comment by beanjoe** [comment]
哦哦，万分感谢。重新下载了，现在可以运行demo了。
