### ISSUE TITLE
还是不太懂rasa-nlu-gao怎么用

### ISSUE THREAD

**Issue by BI4O** [GaoQ1/rasa_chatbot_cn#68]

**Comment by BI4O** [comment]
我把原来的rasa_chatbot_cn中的config.yml的pipline改成了rasa-nlu-gq中的其他pipline，然后重新训练模型rasa train 就报了一大堆错，我想是不是我应该把rasa-nlu-qg整个拖到rasa_chatbot_cn的文件夹里面？如果不是的话，我要怎么使用qg里面提到的其他pipline?

**Comment by GaoQ1** [comment]
README里我说的很清楚了啊

**Comment by nihuizhidao** [comment]
以anaconda环境为例：

1. 因为rasa要使用到httptools这个包，pip安装的时候需要编译，比较复杂，所以先用conda安装这个：
`conda install -c conda-forge httptools`

2. git clone rasa_chatbot_cn，或者直接下载zip包，解压

3. `pip install -r requirements.txt`，这一步会安装rasa_gao所需的所有东西，rasa_chatbot_cn里事实上只有policy文件夹里有不同于原生rasa `init生成的内容，这个文件夹里是添加了attention的policy，你可以按照readme里面写的那些调用这个配置。

4. 在rasa_chatbot_cn文件夹下进行训练
