### ISSUE TITLE
百度的ERNIE有没有类似bert-serving-server的库

### ISSUE THREAD

**Issue by nihuizhidao** [GaoQ1/rasa_chatbot_cn#69]
@GaoQ1 

大神你知道目前是否有使用ERNIE算法的，类似bert-serving-server的库或者是封装成服务可以调用的API么？想在NLU训练的时候换成ERNIE试试。

欢迎各位一起探讨！

**Comment by GaoQ1** [comment]
可以做，但是还没有类似bert-as-service的库
