### ISSUE TITLE
训练非常慢啊

### ISSUE THREAD

**Issue by iorilu** [GaoQ1/rasa_chatbot_cn#7]
用了configs/nlu_model_config.yml训练非常慢, 有什么模型可以训练快点, 效果合适的吗

**Comment by GaoQ1** [comment]
换个component，不要用mitie，用embedding component

**Comment by iorilu** [comment]
刚想试着跑下, 有些问题
1. 默认的train-dialogue 任务没有, 后来看了下,用了train-dialogue-keras
2. 训练好后运行,python -m rasa_core_sdk.endpoint --actions actions &
python -m rasa_core.run --nlu models/nlu/default/current --core models/dialogue_keras --endpoints endpoints.yml

 报错ValueError: Unknown layer:name

**Comment by iorilu** [comment]
研究了下, 貌似tensorflow问题, 更新到新版就可以
