### ISSUE TITLE
RASA多用户并发测试时效果变差

### ISSUE THREAD

**Issue by nihuizhidao** [GaoQ1/rasa_chatbot_cn#70]
不知道大家有没有遇到这个问题，单个用户测试时，NLU和Core的预测结果都很好，但是多用户并发时，效果就突然变差，预测结果很差。我怀疑是不是用户之间的信息“串台”了，但是并不确定，也不能确定到底是scoket串了，还是RASA的问题。

我使用的config.yml如下：

> language: "zh"
> 
> pipeline:
> - name: "JiebaTokenizer"
>   dictionary_path: extra_data/custom_dict
> - name: "rasa_nlu_gao.featurizers.bert_vectors_featurizer.BertVectorsFeaturizer"
>   ip: '127.0.0.1'
>   port: 5555
>   port_out: 5556
>   show_server_config: True
>   timeout: 10000
> - name: "rasa_nlu_gao.classifiers.embedding_bert_intent_classifier.EmbeddingBertIntentClassifier"
> - name: "CRFEntityExtractor"
> 
> policies:
> - name: KerasPolicy
>   epochs: 400
>   max_history: 5
>   learning_rate: 0.003
> - name: MemoizationPolicy
>   max_history: 5
> - name: MappingPolicyMutilAction
> - name: FallbackPolicy
>   nlu_threshold: 0.2
>   core_threshold: 0.1

使用的架构是前端服务器，RASA服务器，以及独立的action server。

**Comment by GaoQ1** [comment]
不同的用户信息是用sender_id控制的
