### ISSUE TITLE
执行make train遇到BertVectorsFeaturizer Unknown component name.

### ISSUE THREAD

**Issue by java2coffee** [GaoQ1/rasa_chatbot_cn#74]
Exception: Failed to find component class for 'rasa_nlu_gao.featurizers.bert_vectors_featurizer.BertVectorsFeaturizer'. Unknown component name.

看到readme里提示设置：export PYTHONPATH=/path/to/your/component
我尝试设置export PYTHONPATH=/Users/jackli/opt/anaconda3/envs/rasa-mobile-env/lib/python3.6/site-packages/rasa_nlu_gao/featurizers
不起作用！

请问如何解决

**Comment by QinWinner** [comment]
先安装好rasa-nlu-gao 导入的export PYTHONPATH= 这个是demo里面一个comoinent的文件夹
不是这个conda里面这个
