### ISSUE TITLE
make train仍报错

### ISSUE THREAD

**Issue by HsiaYu** [GaoQ1/rasa_chatbot_cn#79]
![image](https://user-images.githubusercontent.com/43852251/78135315-44e2a380-7454-11ea-8cf2-815bcd73e62f.png)
仍然报的这个错，已经按readme添加了PYTHONPATHbi并验证如下：
![image](https://user-images.githubusercontent.com/43852251/78135448-7e1b1380-7454-11ea-8d30-b3a4fdb144fa.png)

**Comment by HsiaYu** [comment]
import client.ConcurrentBertClient出错，在相应文件中将其改成了BertClient。

**Comment by GaoQ1** [comment]
可能是版本问题
