### ISSUE TITLE
训练rasa_nlu出错

### ISSUE THREAD

**Issue by fangxiang00** [GaoQ1/rasa_chatbot_cn#82]
TimeoutError: no response from the server (with "timeout"=10000 ms), please check the following:is the server still online? is the network broken? are "port" and "port_out" correct? are you encoding a huge amount of data whereas the timeout is too small for that?
请问怎么解决，感谢！

**Comment by fangxiang00** [comment]
安装bert_as_service时出错：tensorflow.python.framework.errors_impl.NotFoundError: /chinese_L-12_H-768_A-12/bert_config.json; No such file or directory
按照git上教程来的，不知道为什么出错

**Comment by GaoQ1** [comment]
这个你需要看下[bert-as-service](https://github.com/hanxiao/bert-as-service)，你这个问题是没有下载对应的预训练模型

**Comment by fangxiang00** [comment]
你好，这个问题已经解决了，发现是bert_as_service和rasa_nlu_gao版本冲突的问题，现在模型已经训练完了，调用run-cmdline的时候出现错误：
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -3] Temporary failure in name resolution
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
Makefile:15: recipe for target 'run-cmdline' failed
make: *** [run-cmdline] Error 1
请问是哪里出了问题，感谢回复！

**Comment by GaoQ1** [comment]
你endpoints.yml下面配置了mongo，但是你本地或者对应服务器上没有mongod。这个是用来存储对话信息的，你不想存的可以把对应的配置注释掉

**Comment by fangxiang00** [comment]
非常感谢，问题已解决。
